language: python
sudo: false

install:
  - pip install --upgrade pip tox

script:
  - tox -e py27
  - tox -e py34
  - tox -e lint
  - tox -e cover
  - tox -e system-tests
  - tox -e system-tests3
  - scripts/update_docs.sh

after_success:
  - tox -e coveralls

deploy:
  provider: pypi
  user: gcloudpypi
  password:
    secure: LR0i9Oeu6kpLTYS5xK/zCng4gmdtPvFfD/XYdQhyY5jBibQkC2WUQU6nJA9bDXRxhBP5bUwXFGkbhOcOJgHNrUfmyPzpDbM8BR29KfY0WfdYv72gsGZOaekqCReFmHbqLE7qOQtHR5U3ey6ivcgw+hZO72Uu6qDCc9B8qwoBfAs=
  on:
    tags: true
    repo: GoogleCloudPlatform/google-cloud-python
    all_branches: true
  # 'bdist_wheel' builds disabled until #1879 et al. are resolved.
  distributions: "sdist"

cache:
  directories:
    - ${HOME}/.cache/pip
